'use client';
import { useEffect, useState } from 'react';
import { TopBar } from '@/components/TopBar';
import { useUser } from '@/components/AuthGate';
type Account = { id: string; username: string; role: 'admin' | 'user'; disabled: number };
export default function AdminPage() {
  const me = useUser(); const [users, setUsers] = useState<Account[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function load() { const r = await fetch('/api/admin/users'); const d = await r.json(); if (!r.ok) throw new Error(d.error); setUsers(d.users); }
  // State changes happen after fetching the account list.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load().catch(e => setError(e.message)); }, []);
  async function update(user: Account, patch: Partial<Account>) { setBusy(true); setError(''); try { const value = { ...user, ...patch }; const r = await fetch('/api/admin/users', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: user.id, role: value.role, disabled: !!value.disabled }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); await load(); } catch(e) { setError(e instanceof Error ? e.message : '操作失败'); } finally { setBusy(false); } }
  return <><TopBar /><main className="container"><section className="compact-hero"><span className="eyebrow">ADMINISTRATION</span><h1>账号管理</h1><p className="muted">权限调整和停用会使该账号退出登录。个人角色和对话按账号隔离。</p></section>{error && <p role="alert" className="error">{error}<button className="button" onClick={() => void load().catch(e => setError(e.message))}>重试</button></p>}<form className="admin-row card" onSubmit={async e => { e.preventDefault(); const form = e.currentTarget; const data = new FormData(form); setBusy(true); setError(''); try { const r = await fetch('/api/admin/users', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: data.get('username'), password: data.get('password') }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); form.reset(); await load(); } catch(e) { setError(e instanceof Error ? e.message : '创建失败'); } finally { setBusy(false); } }}><input className="input" aria-label="新账号用户名" name="username" placeholder="用户名（3–32 位）" pattern="[a-zA-Z0-9_]{3,32}" required autoComplete="off" /><input className="input" aria-label="新账号密码" type="password" name="password" placeholder="密码（至少 10 位）" minLength={10} maxLength={128} autoComplete="new-password" required /><span className="muted">默认普通用户</span><button className="button primary" disabled={busy}>创建账号</button></form><div className="admin-list">{users.map(user => <div className="admin-row card" key={user.id}><strong>{user.username}{user.id === me?.id ? '（当前账号）' : ''}</strong><span>{user.disabled ? '已停用' : '正常'}</span><select aria-label={`${user.username}的角色`} className="input" disabled={busy || user.id === me?.id} value={user.role} onChange={e => void update(user, { role: e.target.value as Account['role'] })}><option value="user">普通用户</option><option value="admin">管理员</option></select><button className="button" disabled={busy || user.id === me?.id} onClick={() => void update(user, { disabled: user.disabled ? 0 : 1 })}>{user.disabled ? '启用' : '停用'}</button></div>)}</div></main></>;
}
