import * as r0 from './routes/observability/runs/route';
import * as r1 from './routes/conversations/route';
import * as r2 from './routes/ollama/models/route';
import * as r3 from './routes/admin/users/route';
import * as r4 from './routes/evaluations/route';
import * as r5 from './routes/characters/route';
import * as r6 from './routes/chat/route';
import * as r7 from './routes/tts/route';
import * as r8 from './routes/characters/[id]/knowledge/index/route';
import * as r9 from './routes/characters/[id]/knowledge/route';
import * as r10 from './routes/characters/[id]/memories/route';
import * as r11 from './routes/characters/[id]/share/route';
import * as r12 from './routes/conversations/[id]/route';
import * as r13 from './routes/characters/[id]/route';
import * as r14 from './routes/tool-calls/[id]/route';
import * as r15 from './routes/shares/[token]/route';
import * as r16 from './routes/auth/[action]/route';
export const routes = [
{ path: '/api/observability/runs', handlers: r0 },
{ path: '/api/conversations', handlers: r1 },
{ path: '/api/ollama/models', handlers: r2 },
{ path: '/api/admin/users', handlers: r3 },
{ path: '/api/evaluations', handlers: r4 },
{ path: '/api/characters', handlers: r5 },
{ path: '/api/chat', handlers: r6 },
{ path: '/api/tts', handlers: r7 },
{ path: '/api/characters/[id]/knowledge/index', handlers: r8 },
{ path: '/api/characters/[id]/knowledge', handlers: r9 },
{ path: '/api/characters/[id]/memories', handlers: r10 },
{ path: '/api/characters/[id]/share', handlers: r11 },
{ path: '/api/conversations/[id]', handlers: r12 },
{ path: '/api/characters/[id]', handlers: r13 },
{ path: '/api/tool-calls/[id]', handlers: r14 },
{ path: '/api/shares/[token]', handlers: r15 },
{ path: '/api/auth/[action]', handlers: r16 }
];
